name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache go deps
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashfiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        cache: true
        go-version: 1.23
      env:
        GOFLAGS: -mod=mod

    - name: Setup cfssl
      run: go install github.com/cloudflare/cfssl/cmd/cfssl@v1.6.4
    - run: go install github.com/cloudflare/cfssl/cmd/cfssljson@v1.6.4

    - name: Generate test certificates
      run: make init && make gencert

    - name: Setup protoc
      run: sudo apt install -y protobuf-compiler

    - name: Protoc version
      run: protoc --version

    - run: go install google.golang.org/protobuf/...@latest

    - name: Install protocol compiler plugins
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
    - run: go install google.golang.org/grpc/...@latest
    - run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Run protoc
      run: |
        protoc api/v1/*.proto --go_out=. --go-grpc_out=. \
          --go_opt=paths=source_relative \
          --go-grpc_opt=paths=source_relative \
          --proto_path=.

    - name: Build
      run: go build -v ./...

    - name: Test
      run:  make test
