name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cache go deps
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashfiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        cache: true
        go-version: 1.19
      env:
        GOFLAGS: -mod=mod

    - name: Setup protoc
      run: sudo apt install -y protobuf-compiler

    - name: Protoc version
      run: protoc --version

    - run: go install google.golang.org/protobuf/...@latest

    - name: Install protocol compiler plugins
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
    - run: go install google.golang.org/grpc/...@latest
    - run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Run protoc
      run: |
        protoc api/v1/*.proto --go_out=. --go-grpc_out=. \
          --go_opt=paths=source_relative \
          --go-grpc_opt=paths=source_relative \
          --proto_path=.

    - name: Build
      run: go build -v ./...

    - name: Test
      run:  go test -v -cover -p 1 ./...
