name: Golangci lint
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: actions/checkout@v3

      - name: Setup protoc
        run: sudo apt install -y protobuf-compiler

      - name: Protoc version
        run: protoc --version

      - run: go install google.golang.org/protobuf/...@latest

      - name: Install protocol compiler plugins
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - run: go install google.golang.org/grpc/...@latest
      - run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Run protoc
        run: |
          protoc api/v1/*.proto --go_out=. --go-grpc_out=. \
            --go_opt=paths=source_relative \
            --go-grpc_opt=paths=source_relative \
            --proto_path=.

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --enable lll
          version: latest
