name: Golangci lint
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - uses: actions/checkout@v4

      - name: Setup protoc
        run: sudo apt install -y protobuf-compiler

      - name: Protoc version
        run: protoc --version

      - run: go install google.golang.org/protobuf/...@v1.36.0

      - name: Install protocol compiler plugins
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.0
      - run: go install google.golang.org/grpc/...@v1.56.3
      - run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

      - name: Run protoc
        run: |
          protoc api/v1/*.proto --go_out=. --go-grpc_out=. \
            --go_opt=paths=source_relative \
            --go-grpc_opt=paths=source_relative \
            --proto_path=.

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          args: --enable lll
          version: "v2.0.1"
