---
name: YAML Lint

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  yamllint:
    name: YAML Lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint .
